### PR TITLE
Fix gulp ignore

### PR DESCRIPTION
**Pull request by julian1**

### CODE REVIEW

**Comment by ryepdx** [comment]
I'm sorry, but I think this pull request breaks the normal "ignore" functionality.

**Comment by julian1** [comment]
In dapple/node_modules/gulp-match/index.js theres a test for a zero length array and it throws if that's the case. We just change the value to fit the expectation of the gulp-match.

```
 33   if (Array.isArray(condition)) {
 34 
 35     // FRAGILE: ASSUME: it's a minimatch expression
 36     if (!condition.length) {
 37       throw new Error('gulp-match: empty glob array');
 38     }
```

**Comment by ryepdx** [comment]
Ah, sorry. I mixed this one up with #67. Yeah, this looks like it should work. I'm writing a test for this failure mode and will merge your commit in if it passes it. :-)

**Comment by julian1** [comment]
Yes, I jumped the gun with https://github.com/NexusDevelopment/dapple/pull/67, and didn't see the override behavior.

**Comment by ryepdx** [comment]
Looks good to me! Thanks.

**Pull request merged**
