### PR TITLE
Feature/travis

### LINKED ISSUE #109: travis build error when pulling NexusDev dependency
Anyone have any experience with travis?

```
npm ERR! not a package /tmp/npm-2152-QVY4CTU9/github.com/NexusDevelopment/EtherSim.git
npm ERR! Error: ENOENT, open '/tmp/npm-2152-QVY4CTU9/github.com/NexusDevelopment/EtherSim.git-unpack/package.json'
```

### PR DESCRIPTION
**Pull request by mhhf**
use git+http in package.json
see: https://docs.npmjs.com/how-npm-works/packages

closes #109

+ add travis badge to readme

### CODE REVIEW

**Comment by ryepdx** [comment]
I suspect the build failure on this one might have something to do with the version of Node. `node --version` in the development Docker I've been using returns `v5.1.1`, but I'm seeing `v0.10` in the Travis output.

**Comment by mhhf** [comment]
The issue #109 was because travis couldn't load the `ethersim` package because it missed the `git+` prefix. Travis fails now because the old node version could only use ES2015 features, if it was in strict mode ("use strict";). We can either add strickt mode to js files or upgrade the node version. Which one would you suggest?

**Comment by ryepdx** [comment]
It appears `lib/loggers.js` already begins with a `'use strict';` line, so that's strange. At any rate, upgrading Node is probably the best option. Our Travis build environment should match our "official" development environment as much as possible.

**Comment by mhhf** [comment]
oh sorry, actually didn't look it up if it actually is in strict mode... strange
However, node version is now set to 5.1 with npm version 3.3.12, but now the making of `secp256k1@2.0.10` fails. Thoughts?

**Comment by ryepdx** [comment]
Looks like you need a version of gcc installed that supports C++11 features.

**Comment by mhhf** [comment]
haha thanks :) added it.
now stream test if failing. But i don't think its an issue with travis

**Comment by ryepdx** [comment]
Yup! Looks like it can't find one of the test fixtures. Probably because they weren't in the git repo. I've added them and issued a PR.

**Comment by mhhf** [comment]
the last test fails because the dir path is optimized for docker

**Comment by ryepdx** [comment]
Looking into it now.

**Comment by ryepdx** [comment]
Looking into the path error now.

**Comment by mhhf** [comment]
> This seems less than ideal. Why does 7f0ea47 fix the VMTest error? Did it fix it, or just hide it by ignoring the error?
Took it back in in c43de9c
but not handle it, because a possible error is propagated further where we test if we actually expect this error. (`testThrow`)

**Comment by ryepdx** [comment]
I think it'd be ideal to handle an error during the transaction upon receiving the error as part of the transaction callback. Especially since it's possible for the ensuing `getTransactionReceipt` call to fail if `txHash` is null. Empty `if` statements also tend to make me cringe a little.

Anyway, I think I see a pretty simple refactor that handles the issue, so I'll go ahead and implement it.

**Comment by ryepdx** [comment]
Refactored and PR issued. I'll merge this in once you've merged those in, unless you have any objections to what I've written.

**Comment by mhhf** [comment]
Thanks for this :)  I merged it.

**Pull request merged**
