### PR TITLE
Feature/improve tests

### PR DESCRIPTION
**Pull request by mhhf**
implement new test functions:

* function with the exact function names: `testThrow`, `testError`, `testFail` are interpreted as passing, iff the function fails in one of this cases:
    * if an assertion is interpreted as false
    * if the contract throws an error
* test function with the modifier `expectEvent( <name> )` are interpreted as passing, iff they trigger an arbitrary event with the of <name> type

Example: testFail function is interpreted as fail, because the expected event `much` don't match with the regex `^secure$`
```
contract MyTest is Test {
  
    event very(bytes val);
    event much(bytes test);

    function testFail() expectEvent("very") expectEventArg("much", "^secure$") {
      very("exception");
      much("example");
      assertTrue(true);
    }
}
```

### CODE REVIEW

**Comment by nmushegian** [comment]
`expectEventArg` requires you to pack your own calldata for the argument. There is also no way to assert an event *didn't* fire.

My approach would be to have functions `expectEvents(address on_whom)` and `expectEventsExact(address)`. The usage is `expectEvents(my_target);  MyEvent(arg1, arg2); my_target.triggerMyEvent(arg1, arg2)`. The normal version requires the target to fire a superset of events we expect. The `Exact` version requires the target to have fired the exact same sequence as what we expect.

**Comment by mhhf** [comment]
> There is also no way to assert an event didn't fire. 
you're right on this one. 

I'm not sure I understand your approach correctly...
Suppose I want to test if the event `foo` is not thrown in the `testEvent` call, how would your Test contract look like?
```
contract EventTest is Test {
  
    event foo(bytes val);

    // to test if foo is not thrown
    function testEvent() {
      foo("uiuiui");
    }
}
```

Otherwise a modifier can be implemented `expectNoEvent( <name> )`

**Comment by nmushegian** [comment]
Your specific example is a weird edge case that isn't possible because the `Test` contract itself is already "magic". The intent is to "watch" other contracts. Here's how you would test "no event should fire":

```
contract EventDefinitions {
    event foo();
}
contract MyContract is EventDefinitions {
    function noevent() {
        // nothing!
    }
}

MyContractTest is Test, EventDefinitions {
    MyContract _target;
    function setUp() {
        _target = new MyContract();
    }
    function testNoEvent() {
        expectEventsExact(_target);
        // *don't* call foo()   here to signal we *don't* expect it.
        _target.noevent();
    }
}
```

**Comment by nmushegian** [comment]
> function with the exact function names

should be

> function whose name starts with

**Comment by mhhf** [comment]
Ah ok. I see the use case for this.
But I still like the modifier approach as well because of dapples magic. What do you think are the disadvantages for the modifiers/ do you them colliding with your approach `expectEventsExact(_target)` or can they exist im parallel?

I think this simple test case would be much more complicate with instantiating a target:
```
contract EventTest is Test {

    event foo(bytes val);

    // to test if foo is not thrown
    function testEvent() expectEvent("foo") {
      // something, that triggers foo( <bar> );
    }
}
```

**Comment by mhhf** [comment]
> function whose name starts with
done with this

**Comment by nmushegian** [comment]
I'm not sure that reflects a real use case though. You're not testing any outside code there. To do that you would have to have `Test` inherit some other class. I suppose one advantage of going that way is instead of `setUp` you could just specify super-constructor arguments in the Test constructor. But also I'm not sure we can support all of the harness magic using this pattern.

The problem with the modifiers approach is it is too hard to test arguments. I want to harness the one advantage of testing solidity-with-solidity which is the exact match between spec and behavior, ie, I emit the exact same event I expect on the testee.

**Comment by mhhf** [comment]
i see
will try to implement this asap

**Comment by nmushegian** [comment]
also https://github.com/NexusDevelopment/dapple/issues/103

**Comment by ryepdx** [comment]
@mhhf We're switching to [Semistandard style](https://github.com/Flet/semistandard) per #86. I just finished converting everything over so it passes the `semistandard` checker and merged that into `master`, which has created merge conflicts with this PR. Please let me know if you would like some help resolving those.

**Comment by mhhf** [comment]
merged your changes except for `lib/vmtest.js` as it's just style changes. I'll setup the semistandart style guide during the next days and apply it to this file.

**Comment by ryepdx** [comment]
Alright, thanks.

**Comment by ryepdx** [comment]
Heads up: I'm going ahead and reformatting the vmtest files, as I've already got the tool set up and am eager to get this merged in.

**Pull request merged**
