### PR TITLE
Implement new-test command.

### PR DESCRIPTION
**Pull request by drupalnomad**

### CODE REVIEW

**Comment by ryepdx** [comment]
Per Nikolai's suggestions in #22: change `new-test` to `new test` and then move the inline Solidity code in `writeNewTest` out of that function and into a Lodash template in the `constants` directory (see `Builder.compileJsModule` in `lib/build.js` for an example), and then I'll be happy to merge this in.

**Comment by drupalnomad** [comment]
`template.sol` and `template_test.sol` already exist in `constants`. They are exactly what I need, but they are in a different template system. Are these templates being used anywhere else, or should I just convert them to Lodash?

**Comment by nmushegian** [comment]
You should convert them :+1:

**Comment by ryepdx** [comment]
Thanks!

**Pull request merged**
